spring.application.name=auth

# Server Configuration
server.servlet.context-path=/auth
server.forward-headers-strategy=framework

# Return JSON errors instead of Whitelabel HTML error page
spring.web.resources.add-mappings=false

# JWT
jwt.access-token.private-key=YOUR_BASE64_KEY
jwt.access-token.public-key=YOUR_BASE64_KEY
jwt.access-token.expiration=300000
jwt.refresh-token.private-key=YOUR_BASE64_KEY
jwt.refresh-token.public-key=YOUR_BASE64_KEY
jwt.refresh-token.expiration=604800000
jwt.issuer=kaugroups

# Oauth2
app.oauth2.redirect-uri=http://localhost:3000/oauth2/redirect
app.cookie.domain=
# If you want to restrict login to a specific domain set this value below
app.oauth2.hosted-domain=
spring.security.oauth2.client.registration.google.client-id=CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=profile,email

# Genderize
genderize.service.url=http://genderize-service
spring.jackson.mapper.accept-case-insensitive-enums=true

# Database
spring.datasource.url=jdbc:h2:mem:dev-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
